
services:
  app_migrations:
    restart: 'no'
    image: ${MIGRATIONS_APP:-migrations}:${VERSION:-latest}
    command: bun run db:migrate
    volumes:
      - sqlite_db:/app/${SQLITE_FILEPATH}
    environment:
      - DATABASE_URL="sqlite3:${SQLITE_FILEPATH}"
      - DBMATE_MIGRATIONS_DIR=./database/migrations
      - DBMATE_NO_DUMP_SCHEMA=true
  app:
    restart: unless-stopped
    image: ${APP_IMAGE}:${VERSION:-latest}
    volumes:
      - sqlite_db:/app/${SQLITE_FILEPATH}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=production
      - SQLITE_FILEPATH=${SQLITE_FILEPATH}
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN}
    depends_on:
      app_migrations:
        condition: service_completed_successfully

volumes:
  sqlite_db: